# Generated by Django 5.0.4 on 2025-06-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WAFLog',
        ),
    ]
